cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name='search'

urlpatterns = [
    path('',views.search_result,name='search_result'),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
    path('',views.AllprodCat,name='AllprodCat'),
    path('<slug:c_slug>/',views.AllprodCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdDetail,name='ProdDetail'),
]

cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=200,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

search/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:ProdDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ['name']
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.

def search_result(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

shop/views.py
from django.shortcuts import render, get_object_or_404
from. models import Category,Product
from django. core. paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.

def AllprodCat(request,c_slug=None):
    global paginator
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1

    try:
        products = paginator.page(page)

    except(EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})

def ProdDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)

    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Padauk&display=swap" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div>

{% include 'header.html' %}
{% include 'navbar.html' %}

    {% block content %}
 
    {% endblock %}

</div>

{% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the cart page, proceed to review your items and place the order.
{% endblock %}

{%  block title %}
    Cart- V-Shop
{% endblock %}


{% block content %}

{% if not cart_items %}
<div>
    <div class="text-center"><br>
        <h2 class="text-center my_title">
            Your shopping cart is empty
        </h2><br>
        <h5 class="text-center">
            Please click  <a href="{% url 'shop:AllprodCat' %}">here</a>to continue shopping
        </h5>
    </div>
</div>
{% else %}
<div>
    <div class="text-center"><br>
        <h2 class="text-center my_title">
            Your shopping cart
        </h2><br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center ">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="error" style="width:100px;height:100px" class="float-left rounded custom_image"> </a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: ₹{{cart_item.product.price}}<br>
                    Quantity: {{cart_item.quantity}} x  {{cart_item}}
                </td>
                <td>
                    ₹{{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a" > <i class="fa fa-plus custom_icon"></i></a>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"> </i></a>
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"> </i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>

            </thead>
            <tbody>
            <tr>
                <td>
                    Please Review Your Shopping Cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
                <td class="text-center">
                    Your total is : <strong>{{ total }}</strong>

                </td>
            </tr>
            </tbody>

        </table>
        <div class="mx_auto">
            <a href="{% url 'shop:AllprodCat' %}" class="btn btn-secondary btn-block"><h6>Continue Shopping</h6></a>
            <a href="{% url 'shop:AllprodCat' %}" class="btn btn-success btn-block"><h6>Place order</h6></a>

        </div><br>

    </div>

</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:150}}
    {% else %}
        Welcome to V-Shop where you can buy different items
    {% endif %}
{% endblock %}

{% block title %} V-Shop

    {% if category %}
        {{category.name}}
    {% else %}
        See all collections
    {% endif %}

{% endblock %}

{% block content %}

    
    <div class="container-fluid">
        <div class="row-fluid">
            {% if category %}
            <img style="width: 100%;height:50%;padding-block: 1rem;padding-left: 20rem; padding-right: 20rem;" class="my_image catesize" src="{{ category.image.url }}" alt="{{ category.name }}">
        </div><br>
            <h4 class="text-center my_title">{{category.name}}</h4>
        <p class="text-justify">
            {{category.description}}
        </p>
    </div>

            {% else %}
    <div class="container-fluid">
        <div class="">
            <img style="width: 100%; height:20rem;" src="{% static 'image/banner.png' %}" class="img-fluid img-thumbnail" alt="Our Products">
        </div>
    </div>
    <br>
    <div class="container-fluid">
        <div class="">
            <h4 class="text-center my_title">ALL PRODUCT COLLECTIONS</h4>
        </div>
    </div><br>

    {% endif %}

        <div class="container-fluid">
            <div class="row mx-auto">
                {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-12 col-lg-4" style="padding-block:1rem; padding-right: 5rem;padding-left: 5rem;">
                    <div class="card">
                        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}" class="card-img-top img-fluid" style="width:27rem; height:22rem;"></a>
                        <h5 style="padding:.4rem;">{{product.name}}</h5>
                        <h5 class="price" style="padding:.4rem;">₹ {{product.price}}</h5>
                    {% if product.stock <= 0 %}
                        <a class="my_style"><b>Out of stock</b></a>
                    {% else %}

                        <span class="fa fa-star checked" style="padding:.4rem;">
                        <span class="fa fa-star checked">
                        <span class="fa fa-star"></span></span></span>
                    {% endif %}

                     </div>
                </div>
                {% endfor %}
            </div><br>

            <div class="paginator">
                <div class="mx-auto">

                {% if products.paginator.num_pages > 1 %}
                <hr>

                    <div class="text-center">

                        {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                        {% endfor %}

                    </div><br>
                        {% endif %}
                </div>
            </div>
        </div>

{% endblock %}

templates/footer.html
<div class="container-fluid">
  <div class="footer navbar-fixed bottom my_footer">
    <p class="text-center">&copy; V-Shop Ltd, All rights reserved</p>
  </div>
</div>

templates/header.html
{% load static %}
<div class="container-fluid"
<header style="background-color: #ffff">
    <center>
        <a href="{% url 'shop:AllprodCat' %}" > <img src="{% static 'image/logo.png' %}" alt="LogoPng" width="400px" height="100px">
    </center>
</header>
</div>

templates/navbar.html
{% load static %}
<br>
<nav class="navbar navbar-expand-lg bg-#A1B8C0" style="padding:0rem">

  <div class="container-fluid" >

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:AllprodCat' %}">Home</i></a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Show All
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:AllprodCat' %} ">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail'  %}" ><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search:search_result' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" ></i></button>
      </form>
    </div>
  </div>

</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

  {{product.description|truncatewords:155}}

{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }}
    {% endif %}
{% endblock %}
{% block content %}
<br>
<div class="container-fluid">
    <div class="mx_auto">
        <p>
            <a href="{% url 'shop:AllprodCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}
        </p>
    </div>
</div>

    <br>
        <div class="row">
            <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div class="">
                    <img  src="{{product.image.url}}" alt="{{product.name}}">
                </div>
            </div>
    
                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="container-fluid">
                    <h1 class="my_product_title">{{product.name}}</h1>
                    <p>₹ {{product.price}}</p>
                    <p class="my_title">Product Description</p>
                    <p class="text-justify my_prod_text">{{product.description}}</p>
    
                    {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                    {% endif %}
    
                    </div>
                </div>
            
        </div>
    </div><br><br>

{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have variety of products
{% endblock %}
{% block title %}
    Search Page
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">
    You have searched for :<b>"{{query}}"</b>
    </p>
</div>

<div class="container">
        <div class="row mx_auto">
                {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-12 col-lg-3" style="padding:.5rem">
                    <div class="card text-center">
                        <a href="{{product.get_url}}"><img src="{{product.image.url}}" class="card-img-top" alt="{{product.name}}" width="320px" height="240px"></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                {{product.name}}
                            </h4>
                            <p class="card-text">
                                ₹{{product.price}}
                            </p>
                        </div>
                    </div>
                </div>

                {% empty %}
            <div class="row mx_auto">
                <p class="text-center my_search_text">
                    0 Results found
                </p>
            </div>

                {% endfor %}
    </div>
</div><br><br>

{% endblock %}